version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: capstone-postgres
    environment:
      POSTGRES_DB: capstone-bbdd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OFDXHJlGMF7g9dls6JmJhyMDLEwdAMfuyoDV6StqLa9LywYc2I77mMJtRrMFu5QC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: capstone-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/capstone-bbdd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=OFDXHJlGMF7g9dls6JmJhyMDLEwdAMfuyoDV6StqLa9LywYc2I77mMJtRrMFu5QC

volumes:
  postgres_data:
